general {
    col.active_border = rgba(A78BFAff) rgba(7C5CDBff) 45deg
    col.inactive_border = rgba(1A1A2444)
}

group {
    col.border_active = rgba(A78BFAff)
    col.border_inactive = rgba(1A1A2444)
    col.border_locked_active = rgba(FF6B6Bff)
    col.border_locked_inactive = rgba(1A1A2444)

    groupbar {
        col.active = rgba(A78BFAff)
        col.inactive = rgba(1A1A2444)
        col.locked_active = rgba(FF6B6Bff)
        col.locked_inactive = rgba(1A1A2444)
    }
}
